// PNGF-OPT V1.00
//
// Proof-of-concept Direct Binary Search (DBS) optimization example
// using the PNGF method. 
//
//
// Copyright (c) 2025, 2026, Constantine Sideris (sideris@stanford.edu) and Jui-Hung Sun
// (juihungs@usc.edu)
// 
// This program is free software: you can redistribute it and/or modify it under the terms 
// of the GNU Affero General Public License as published by the Free Software Foundation, 
// either version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY 
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
// PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License along with 
// this program. If not, see <https://www.gnu.org/licenses/>. 
// 
// 
// 
// This code will reproduce the Substrate Antenna (SA) example device
// reported in the PNGF paper by Sun, et. al. if the default supplied
// RNG seed is used and the Gmat_sub_01.bin through Gmat_sub_05.bin
// matrices are generated by acmefdfd as described in the instructions
// and placed in the same folder as pngf-opt. 
//
// Known issues: The RNG on MacOS seems to behave differently than the RNG
// on Linux distributions and thus, if this code is run on a Mac, it will
// likely result in a different final design that does not match the one
// in the paper, even if the same RNG seed is utilized.
//

#include <array>
#include <vector>
#include <iostream>
#include <iomanip>
#include <list>
#include <forward_list>
#include <functional>
#include <random>
#include <fstream>
#include <complex>

#include <thread>
#include <chrono>
#include <time.h>

#include <stdio.h>
#include <math.h>
#include <complex>

#include <omp.h>

#include <Eigen>

//#define USE_SINGLE_PRECISION

#ifdef USE_SINGLE_PRECISION
typedef float precision;
float operator"" _d(long double v)
{
    return (float)v;
}
#else
typedef double precision;
double operator"" _d(long double v)
{
    return (double)v;
}
#endif

#if __APPLE__
// use Accelerate framework for Mac:
#include <Accelerate/Accelerate.h>
typedef std::complex<precision> lp_complex;
#else
// Use OpenBLAS/LAPACK on Linux:
#include <cblas.h>
extern "C" {
    void zgetrf_(int*, int*, void*, int*, int*, int*);
    void zgetri_(int*, void*, int*, int*, void*, int*, int*);
    void cgetrf_(int*, int*, void*, int*, int*, int*);
    void cgetri_(int*, void*, int*, int*, void*, int*, int*);
}
typedef std::complex<precision> lp_complex;
#endif

using namespace std;
using namespace Eigen;

using ArrayXr = std::vector<precision>;
using ArrayXcr = std::vector<std::complex<precision>>;
static const std::complex<precision> I1 = std::complex<precision>(0.0, 1.0);

#define eps0            (8.8541878188E-12)
#define mu0             (1.25663706127E-6)
#define c0              (2.997924579998211E8)
#define eta0            (3.767303134118051e+02)

// Defines that determine whether the initial starting point is an empty grid
// with just two pieces of metal (one on either side of the lumped port source),
// or if the tilemap should be randomized before starting the inverse design:
#define INIT_EMPTY      (0)
#define INIT_RANDOM     (1)

#include "acmetime.hpp"
#include "linalg.hpp"
#include "pngfopt.hpp"
#include "magichat.hpp"
#include "logger.hpp"

const int NUM_FREQ = 5;
const precision freqs[5] = {25.0E9, 27.5E9, 30.0E9, 32.5E9, 35.0E9};

precision logsig (precision x)
{
    return 1.0_d / (1.0_d + exp(-x)); //std::log(1.0 / (1.0 + std::exp(-x)));
}

std::string numberToStringWithLeadingZeros (int number, int width)
{
    std::stringstream ss;
    ss << std::setw(width) << std::setfill('0') << number;
    return ss.str();
}

int main (int argc, char **argv)
{
    
    int max_threads;
    acmetime mytime;

    // Set OMP number of cores:
    max_threads = omp_get_max_threads();
    std::cout << "Max OMP threads: " << max_threads << std::endl;
    omp_set_num_threads (max_threads);

    const int tilemap_xsz = 21;
    const int tilemap_ysz = 21;
    // Max tiles that can be flipped in one iteration:
    // (used for memory planning/allocation purposes)
    const int max_flip_cnt = 4;
    // Number of rows in Gobj:
    // For the substrate antenna example, we consider the voltage
    // at the lumped port (to compute S11) and two quantities
    // needed to compute the directivity (D) in the broadside
    // direction for a total of 3 xobj coefficients:
    const int xobj_cnt = 1+2;
    // Set this to 0 to seed it based on timer:
    const int rng_seed = -514213645; 
    const int initial_design = INIT_EMPTY;

    precision lambda_design = 0.01;
    precision dx = lambda_design/60.0_d;
    precision dy = lambda_design/60.0_d;
    precision dz = lambda_design/180.0_d; 

    precision k0[NUM_FREQ];
    for (int i = 0; i < NUM_FREQ; i++)
        k0[i] = 2.0_d*M_PI*freqs[i]/c0;

    std::vector<PNGF_Optimizer> myPNGF;
    std::vector<int> tile_map(tilemap_xsz*tilemap_ysz);

    // Clear the tilemap:
    for (int i = 0; i < tilemap_xsz*tilemap_ysz; i++)
        tile_map[i] = 0;

    int run_index=0;
    if (argc>1) 
        run_index = atoi(argv[1]);
    
    // This is a helper class that draws tile indices to flip
    // without replacement, so that we do not try flipping a tile
    // that we have alrady attempted until we have changed the current
    // state of the tilemap by finding a good flip.
    MagicHat myhat(rng_seed, run_index, ((tilemap_xsz-1)*0.5+1)*((tilemap_ysz-1)*0.5+1)-1);

    // Helper class to log inverse design progress to an array and
    // then export it to a text file:
    Logger mylog (myhat.rng_seed, tilemap_xsz*tilemap_ysz, 10000, 17);

    if (initial_design == INIT_RANDOM)
    {
        // Start from a random initial configuration:
        // (Enforce 2 axis mirror symmetry.)
        for (int j = 0; j < (tilemap_ysz-1)*0.5+1; j++)
        {
            for (int i = 0; i < (tilemap_xsz-1)*0.5+1; i++)
            {
                int tile_state = myhat.rand_binary();
                
                tile_map[i+j*tilemap_xsz] = tile_state;
                if (i < (tilemap_xsz-1)*0.5)
                    tile_map[((tilemap_xsz-1)-i)+j*tilemap_xsz] = tile_state;
                if (j < (tilemap_ysz-1)*0.5)
                {
                    tile_map[i+((tilemap_ysz-1)-j)*tilemap_xsz] = tile_state;
                    if (i < (tilemap_xsz-1)*0.5)
                        tile_map[((tilemap_xsz-1)-i)+((tilemap_ysz-1)-j)*tilemap_xsz] = tile_state;    
                }
            }
        }
    }

    int tile_mid_x = (tilemap_xsz-1)*0.5;
    int tile_mid_y = (tilemap_ysz-1)*0.5;

    // The lumped port takes up the center tile
    // Define the tiles adjacent on either side 
    tile_map[tile_mid_y*tilemap_xsz+tile_mid_x-1] = 1;
    tile_map[tile_mid_y*tilemap_xsz+tile_mid_x+1] = 1;
    tile_map[tile_mid_y*tilemap_xsz+tile_mid_x] = 0;
    tile_map[(tile_mid_y-1)*tilemap_xsz+tile_mid_x] = 0;
    tile_map[(tile_mid_y+1)*tilemap_xsz+tile_mid_x] = 0;

    // Instantiate NUM_FREQ number of PNGF optimizer classes since
    // we need one for each frequency point that we are considering
    // in the optimization:
    myPNGF.resize(NUM_FREQ);

    precision diff;

    mytime.tik();

    // Import the G matrices produced by the FDFD solver and initialize
    // each PNGF class.
    for (int i = 0; i < NUM_FREQ; i++)
    {
        int err;
        std::string fname = "Gmat_sub_" + numberToStringWithLeadingZeros(i+1, 2) + ".bin";
        // Initialize the ith frequency PNGF optimizer class:
        myPNGF[i].init (fname.c_str(), tilemap_xsz, tilemap_ysz, 3, 3, xobj_cnt, max_flip_cnt, dx, dy, dz);
        // Set the intiial tilemap:
        myPNGF[i].set_tile_map (tile_map);
        // Assign the lumped driving port to be in the center of the design:
        myPNGF[i].set_source_port (tile_mid_x, tile_mid_y, 1, 2);
        // Compute the C matrix based on the equation in the paper:
        // C = (I - P) + PG
        myPNGF[i].compute_C_matrix();
        // Compute Cinv as explained in the paper:
        LinAlg::invertMatrix (myPNGF[i].C);
        // Precompute P * Einc:
        myPNGF[i].compute_PEinc();
        // Precompute R and S matrices as defined in the paper:
        // R = Gobj*Cinv
        // S = Cinv*PEinc
        myPNGF[i].compute_R_matrix(1);
    }
    diff = mytime.tok();
    // Report timing for initialization:
    std::cout << "Time elapsed: " << diff << std::endl;

    std::complex<precision> newEobj;
    newEobj = 0;

    int tile_flip[4];

    int tx, ty;

    int num_flip;
    precision magS11[NUM_FREQ], F, F_best, tmp_F[NUM_FREQ];
    precision newD[NUM_FREQ];
    std::vector<precision> perf(17);

    F=0;
    for (int ii = 0; ii < NUM_FREQ; ii++)
    {
        std::complex<precision> Zin, S11;
    
        // Compute the input impedance based on the voltage on the port. Must also include the additional voltage
        // Vinc produced by the incident Jsrc.
        Zin = -(myPNGF[ii].Eobj(0)+myPNGF[ii].Vinc)*dx*0.5_d/(2.0_d*dy*dz);
        // Compute S11 based on 50 ohm Z0:
        S11 = (Zin-50.0_d)/(Zin+50.0_d);
        // Compute the directivity from the Near-Field to Far-Field transformation data in Gobj:
        newD[ii] = (k0[ii]*k0[ii]/(32*M_PI*M_PI*eta0))*real(conj(myPNGF[ii].Eobj(1)+myPNGF[ii].LN1inc)*(myPNGF[ii].Eobj(1)+myPNGF[ii].LN1inc) + 
        conj(myPNGF[ii].Eobj(2)+myPNGF[ii].LN2inc)*(myPNGF[ii].Eobj(2)+myPNGF[ii].LN2inc));
        // Divide by Pin:
        newD[ii] = 4.0*M_PI*newD[ii] / real(-(myPNGF[ii].Eobj(0)+myPNGF[ii].Vinc)*dx*0.5_d*(2.0_d*dy*dz)*0.5_d);
        // Compute the magnitude of S11:
        magS11[ii] = std::abs(S11);

        // Multi-objective function which attempts to balance maximizing directivity while achieving an acceptble S11:
        tmp_F[ii] = 200.0_d*magS11[ii]*magS11[ii] + (15.0_d - newD[ii])*(15.0_d - newD[ii]);

        // Output current performance at frequency ii to stdout:
        std::cout << ii << ": S11: " << 20*log10(magS11[ii]) << " (" << Zin << "), D: " << newD[ii] << std::endl;

        // For output logging:
        perf[2+ii*3+0] = real(S11);
        perf[2+ii*3+1] = imag(S11);
        perf[2+ii*3+2] = newD[ii];
    }
    // Starting objective function:
    F_best = 0;
    for (int ii = 0; ii < NUM_FREQ; ii++)
        F_best += tmp_F[ii];

    perf[0] = F_best;
    perf[1] = F_best;

    std::cout << "starting F: " << F_best; 

    // Output the initial starting tilemap to stdout:
    for (int j = 0; j < tilemap_ysz; j++)
    {
        for (int i = 0; i < tilemap_xsz; i++)
        {
            if (myPNGF[0].tile_map[i+((tilemap_ysz-1)-j)*tilemap_xsz])
                std::cout << "x";
            else
                std::cout << ".";
        }
        std::cout << std::endl;
    }
    
    int last_tried = -1;

    // Initialize the performance logger:
    mylog.record_tilemap_init (tile_map);

    // Record the initial starting point:
    mylog.record_flip (-1, -1, perf);

    int is_done = 0;
    int flip_count = 0;

    mytime.tik();
    // This is the optimization loop. It will continue flipping
    // tiles until it has reached a local minimum, meaning that
    // every tile on the map has been flipped and none of the
    // flips improve the objective function further.
    while (1)
    {
        int rand_tile;

        // Draw a tile to flip from the magic hat:
        while (1)
        {
            rand_tile = myhat.draw();
            if (rand_tile < 0)
            {
                // Ran out of tiles to flip.
                // Must have converged to a local minimum:
                is_done = 1;
                break;
            }
            // 
            ty = rand_tile/((tilemap_xsz-1)*0.5+1);
            tx = rand_tile-ty*((tilemap_xsz-1)*0.5+1);
            if (rand_tile == last_tried)
                continue;
            if ((tx==tile_mid_x) && (ty==tile_mid_y))
                continue; // source tile.
            if ((tx==(tile_mid_x-1)) && (ty==tile_mid_y))
                continue; // metal block next to source.
            // Enforce mirror symmetry on both x and y axes since we would
            // like to maximize the directivity in the broadside direction.
            if (tx==tile_mid_x)
            {
                // If we are on the center x column (on the y axis), only
                // two tiles need to be flipped to maintain the symmetry:
                num_flip=2;
                tile_flip[0] = tx+ty*tilemap_xsz;
                tile_flip[1] = tx+((tilemap_ysz-1)-ty)*tilemap_xsz;
                last_tried = rand_tile;
                break;
            } else if (ty==tile_mid_y) {
                // If we are on the center y row (on the x axis), only
                // two tiles need to be flipped to maintain the symmetry:
                num_flip=2;
                tile_flip[0] = tx+ty*tilemap_xsz;
                tile_flip[1] = ((tilemap_xsz-1)-tx)+ty*tilemap_xsz;
                last_tried = rand_tile;
                break;
            } else {
                // Otherwise, one tile must be flipped in each quadrant
                // for a total of 4 tiles to be flipped:
                num_flip=4;
                tile_flip[0] = tx+ty*tilemap_xsz;
                tile_flip[1] = ((tilemap_xsz-1)-tx)+ty*tilemap_xsz;
                tile_flip[2] = tx+((tilemap_ysz-1)-ty)*tilemap_xsz;
                tile_flip[3] = ((tilemap_xsz-1)-tx)+((tilemap_ysz-1)-ty)*tilemap_xsz;
                last_tried = rand_tile;
                break;
            }
        }
        // If there are no more flips remaining inside the hat, exit out of the while loop
        // since we have reached a local minimum.
        if (is_done)
            break;

        // Compute the objective function after taking the flip. This is very fast using the
        // Woodbury matrix formula to compute a rank update to Cinv, as described in the
        // manuscript. Computing the change in xobj due to a tile flip costs O(Nopt) operations.
        F = 0;
        for (int ii = 0; ii < NUM_FREQ; ii++)
        {
            std::complex<precision> Zin, S11;

            myPNGF[ii].compute_updated_Eobj (tile_flip, num_flip);
            Zin = -(myPNGF[ii].newEobj(0)+myPNGF[ii].Vinc)*dx*0.5_d/(2.0_d*dy*dz);
            S11 = (Zin-50.0_d)/(Zin+50.0_d);
            newD[ii] = (k0[ii]*k0[ii]/(32*M_PI*M_PI*eta0))*real(conj(myPNGF[ii].newEobj(1)+myPNGF[ii].LN1inc)*(myPNGF[ii].newEobj(1)+myPNGF[ii].LN1inc) + 
                                                    conj(myPNGF[ii].newEobj(2)+myPNGF[ii].LN2inc)*(myPNGF[ii].newEobj(2)+myPNGF[ii].LN2inc));
            newD[ii] = 4.0*M_PI*newD[ii] / real(-(myPNGF[ii].newEobj(0)+myPNGF[ii].Vinc)*dx*0.5_d*(2.0_d*dy*dz)*0.5_d);
            magS11[ii] = std::abs(S11); 
            tmp_F[ii] = 200.0_d*magS11[ii]*magS11[ii] + (15.0_d - newD[ii])*(15.0_d - newD[ii]);
            perf[2+ii*3+0]=real(S11);
            perf[2+ii*3+1]=imag(S11);
            perf[2+ii*3+2]=newD[ii];
        }
        F = 0;
        for (int ii = 0; ii < NUM_FREQ; ii++)
            F += tmp_F[ii];

        perf[0] = F;
        perf[1] = F_best;

        // Log the iteration information and performance:
        mylog.record_flip (tx+ty*tilemap_xsz, F < F_best, perf);

        // Check if this flip improved the objective function:
        if ((F < F_best))
        {
            // This was a good flip. Output the updated performance
            // metrics of the design at each frequency:
            std::cout << flip_count << ": ";
            for (int ii = 0; ii < NUM_FREQ; ii++)
                std::cout <<  20.0_d*log10(magS11[ii]) << ",";
            std::cout << " : ";
            for (int ii = 0; ii < NUM_FREQ; ii++)
                std::cout << newD[ii] << ",";
            std::cout << std::endl;

            // Replace the previous best objective function with the
            // latest one:
            F_best = F;
            // Since we found a good flip, we must update Cinv as
            // explained in the manuscript using the Woodbury rank
            // update formula. This costs O(Nopt^2) operations:
            for (int ii = 0; ii < NUM_FREQ; ii++)
            {
                myPNGF[ii].update_C_inv();
                myPNGF[ii].compute_PEinc();
                myPNGF[ii].compute_R_matrix(0);             
            }
            // Replace all of the tiles in the hat since the current state
            // was modified, so any prior flip might be worth trying again:
            myhat.reset();
        }
        // Increase the iteration counter:
        flip_count++;
    }

    // We can only get here once all possible flips have been tried without having
    // found one that can improve the objective function further.
    diff = mytime.tok();
    std::cout << "Time elapsed: " << diff << std::endl;
    
    // Record the final design:
    mylog.record_tilemap_final (tile_map);

    // If an index is provided for the log file, export a text-based log file
    // with the optimization history:
    if (argc>1)
        mylog.save(std::string("log_")+std::to_string(run_index)+std::string(".txt"));
    std::cout << "Converged after " << flip_count << " flips!" << std::endl;

    // Output the final design to stdout using ASCII art:
    std::cout << "Final design:" << std::endl << std::endl;
    for (int j = 0; j < tilemap_ysz; j++)
    {
        for (int i = 0; i < tilemap_xsz; i++)
        {
            if (myPNGF[0].tile_map[i+((tilemap_ysz-1)-j)*tilemap_xsz])
                std::cout << "x";
            else
                std::cout << ".";
        }
        std::cout << std::endl;
    }
    
    return 0;
}